---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-eks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sample-eks
  name: eks-sample-linux-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-eks-pods
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-eks-pods
    spec:
      containers:
      - image: 616532015738.dkr.ecr.ap-northeast-1.amazonaws.com/yamato-k-repository:latest
        imagePullPolicy: Always
        name: sample-eks-pods
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: sample-eks
  name: sample-eks-service-target
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: sample-eks-pods